package com.jokerdemo.crm.domain;
// Generated 2017-10-11 16:18:12 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private int areaid;
	private Area area;
	private String aname;
	private Set areas = new HashSet(0);
	private Set customers = new HashSet(0);

	public Area() {
	}

	public Area(int areaid) {
		this.areaid = areaid;
	}
	
	public Area(int areaid, String aname) {
		super();
		this.areaid = areaid;
		this.aname = aname;
	}

	public Area(int areaid, Area area, String aname, Set areas, Set customers) {
		this.areaid = areaid;
		this.area = area;
		this.aname = aname;
		this.areas = areas;
		this.customers = customers;
	}

	public int getAreaid() {
		return this.areaid;
	}

	public void setAreaid(int areaid) {
		this.areaid = areaid;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	public Set getAreas() {
		return this.areas;
	}

	public void setAreas(Set areas) {
		this.areas = areas;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

}
