package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Association generated by hbm2java
 */
public class Association implements java.io.Serializable {

	private Integer associationid;
	private Customer customer;
	private Date associationtime;
	private String associationplace;
	private String associationoutline;
	private String associationremarks;
	private String associationinfo;

	public Association() {
	}

	public Association(Customer customer, Date associationtime, String associationplace, String associationoutline,
			String associationremarks, String associationinfo) {
		this.customer = customer;
		this.associationtime = associationtime;
		this.associationplace = associationplace;
		this.associationoutline = associationoutline;
		this.associationremarks = associationremarks;
		this.associationinfo = associationinfo;
	}

	public Integer getAssociationid() {
		return this.associationid;
	}

	public void setAssociationid(Integer associationid) {
		this.associationid = associationid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getAssociationtime() {
		return this.associationtime;
	}

	public void setAssociationtime(Date associationtime) {
		this.associationtime = associationtime;
	}

	public String getAssociationplace() {
		return this.associationplace;
	}

	public void setAssociationplace(String associationplace) {
		this.associationplace = associationplace;
	}

	public String getAssociationoutline() {
		return this.associationoutline;
	}

	public void setAssociationoutline(String associationoutline) {
		this.associationoutline = associationoutline;
	}

	public String getAssociationremarks() {
		return this.associationremarks;
	}

	public void setAssociationremarks(String associationremarks) {
		this.associationremarks = associationremarks;
	}

	public String getAssociationinfo() {
		return this.associationinfo;
	}

	public void setAssociationinfo(String associationinfo) {
		this.associationinfo = associationinfo;
	}

}
