package com.jokerdemo.crm.domain;
// Generated 2017-10-11 16:18:12 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chance generated by hbm2java
 */
public class Chance implements java.io.Serializable {

	

	

	public Chance(Integer chanceid, String customername, String outline, String contactsname, String contactsphone,
			Date createtime) {
		super();
		this.chanceid = chanceid;
		this.customername = customername;
		this.outline = outline;
		this.contactsname = contactsname;
		this.contactsphone = contactsphone;
		this.createtime = createtime;
	}

	private Integer chanceid;
	private User userByCreateuserid;
	private User userByAssignuserid;
	private Status status;
	private String source;
	private String customername;
	private int odds;
	private String outline;
	private String contactsname;
	private String contactsphone;
	private String description;
	private Date createtime;
	private Date assigntime;
	private Set plans = new HashSet(0);

	public Chance() {
	}

	public Chance(Status status, int odds, String outline, String contactsname, String contactsphone,
			String description) {
		this.status = status;
		this.odds = odds;
		this.outline = outline;
		this.contactsname = contactsname;
		this.contactsphone = contactsphone;
		this.description = description;
	}

	public Chance(User userByCreateuserid, User userByAssignuserid, Status status, String source, String customername,
			int odds, String outline, String contactsname, String contactsphone, String description, Date createtime,
			Date assigntime, Set plans) {
		this.userByCreateuserid = userByCreateuserid;
		this.userByAssignuserid = userByAssignuserid;
		this.status = status;
		this.source = source;
		this.customername = customername;
		this.odds = odds;
		this.outline = outline;
		this.contactsname = contactsname;
		this.contactsphone = contactsphone;
		this.description = description;
		this.createtime = createtime;
		this.assigntime = assigntime;
		this.plans = plans;
	}

	public Integer getChanceid() {
		return this.chanceid;
	}

	public void setChanceid(Integer chanceid) {
		this.chanceid = chanceid;
	}

	public User getUserByCreateuserid() {
		return this.userByCreateuserid;
	}

	public void setUserByCreateuserid(User userByCreateuserid) {
		this.userByCreateuserid = userByCreateuserid;
	}

	public User getUserByAssignuserid() {
		return this.userByAssignuserid;
	}

	public void setUserByAssignuserid(User userByAssignuserid) {
		this.userByAssignuserid = userByAssignuserid;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public int getOdds() {
		return this.odds;
	}

	public void setOdds(int odds) {
		this.odds = odds;
	}

	public String getOutline() {
		return this.outline;
	}

	public void setOutline(String outline) {
		this.outline = outline;
	}

	public String getContactsname() {
		return this.contactsname;
	}

	public void setContactsname(String contactsname) {
		this.contactsname = contactsname;
	}

	public String getContactsphone() {
		return this.contactsphone;
	}

	public void setContactsphone(String contactsphone) {
		this.contactsphone = contactsphone;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getAssigntime() {
		return this.assigntime;
	}

	public void setAssigntime(Date assigntime) {
		this.assigntime = assigntime;
	}

	public Set getPlans() {
		return this.plans;
	}

	public void setPlans(Set plans) {
		this.plans = plans;
	}

}
