package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	private Integer contactsid;
	private Customer customer;
	private String contactsname;
	private String contactssex;
	private String contactsjob;
	private String contactsphone;
	private Date contactsbirthday;
	private String contactsremarks;

	public Contacts() {
	}

	public Contacts(String contactsname) {
		this.contactsname = contactsname;
	}

	public Contacts(Customer customer, String contactsname, String contactssex, String contactsjob,
			String contactsphone, Date contactsbirthday, String contactsremarks) {
		this.customer = customer;
		this.contactsname = contactsname;
		this.contactssex = contactssex;
		this.contactsjob = contactsjob;
		this.contactsphone = contactsphone;
		this.contactsbirthday = contactsbirthday;
		this.contactsremarks = contactsremarks;
	}

	public Integer getContactsid() {
		return this.contactsid;
	}

	public void setContactsid(Integer contactsid) {
		this.contactsid = contactsid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getContactsname() {
		return this.contactsname;
	}

	public void setContactsname(String contactsname) {
		this.contactsname = contactsname;
	}

	public String getContactssex() {
		return this.contactssex;
	}

	public void setContactssex(String contactssex) {
		this.contactssex = contactssex;
	}

	public String getContactsjob() {
		return this.contactsjob;
	}

	public void setContactsjob(String contactsjob) {
		this.contactsjob = contactsjob;
	}

	public String getContactsphone() {
		return this.contactsphone;
	}

	public void setContactsphone(String contactsphone) {
		this.contactsphone = contactsphone;
	}

	public Date getContactsbirthday() {
		return this.contactsbirthday;
	}

	public void setContactsbirthday(Date contactsbirthday) {
		this.contactsbirthday = contactsbirthday;
	}

	public String getContactsremarks() {
		return this.contactsremarks;
	}

	public void setContactsremarks(String contactsremarks) {
		this.contactsremarks = contactsremarks;
	}

}
