package com.jokerdemo.crm.domain;
// Generated 2017-10-11 16:18:12 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String cuostomerid;
	private Datadictionary datadictionaryByRelationshiplevel;
	private Datadictionary datadictionaryByCredit;
	private Area area;
	private Datadictionary datadictionaryBySatisfaction;
	private User user;
	private String company;
	private Date createtime;
	private String address;
	private Integer postalcode;
	private String phone;
	private String fax;
	private String url;
	private String licenseno;
	private String corporation;
	private Double capital;
	private Double turnover;
	private String bank;
	private String bankaccount;
	private String landtax;
	private String nationaltax;
	private Integer customerstatus;
	private Set services = new HashSet(0);
	private Set orders = new HashSet(0);
	private Set contactses = new HashSet(0);
	private Set churnses = new HashSet(0);
	private Set associations = new HashSet(0);
	private String username;
	private String ddname;
	
	public Customer() {
	}
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDdname() {
		return ddname;
	}

	public void setDdname(String ddname) {
		this.ddname = ddname;
	}

	public Customer(String cuostomerid, String company, String username, String ddname) {
		this.cuostomerid = cuostomerid;
		this.username = username;
		this.ddname = ddname;
		this.company = company;
	}

	public Customer(String cuostomerid, String company) {
		this.cuostomerid = cuostomerid;
		this.company = company;
	}

	public Customer(String cuostomerid, Datadictionary datadictionaryByRelationshiplevel,
			Datadictionary datadictionaryByCredit, Area area, Datadictionary datadictionaryBySatisfaction, User user,
			String company, Date createtime, String address, Integer postalcode, String phone, String fax, String url,
			String licenseno, String corporation, Double capital, Double turnover, String bank, String bankaccount,
			String landtax, String nationaltax, Integer customerstatus, Set services, Set orders, Set contactses,
			Set churnses, Set associations) {
		this.cuostomerid = cuostomerid;
		this.datadictionaryByRelationshiplevel = datadictionaryByRelationshiplevel;
		this.datadictionaryByCredit = datadictionaryByCredit;
		this.area = area;
		this.datadictionaryBySatisfaction = datadictionaryBySatisfaction;
		this.user = user;
		this.company = company;
		this.createtime = createtime;
		this.address = address;
		this.postalcode = postalcode;
		this.phone = phone;
		this.fax = fax;
		this.url = url;
		this.licenseno = licenseno;
		this.corporation = corporation;
		this.capital = capital;
		this.turnover = turnover;
		this.bank = bank;
		this.bankaccount = bankaccount;
		this.landtax = landtax;
		this.nationaltax = nationaltax;
		this.customerstatus = customerstatus;
		this.services = services;
		this.orders = orders;
		this.contactses = contactses;
		this.churnses = churnses;
		this.associations = associations;
	}
	

	public String getCuostomerid() {
		return this.cuostomerid;
	}

	public void setCuostomerid(String cuostomerid) {
		this.cuostomerid = cuostomerid;
	}

	public Datadictionary getDatadictionaryByRelationshiplevel() {
		return this.datadictionaryByRelationshiplevel;
	}

	public void setDatadictionaryByRelationshiplevel(Datadictionary datadictionaryByRelationshiplevel) {
		this.datadictionaryByRelationshiplevel = datadictionaryByRelationshiplevel;
	}

	public Datadictionary getDatadictionaryByCredit() {
		return this.datadictionaryByCredit;
	}

	public void setDatadictionaryByCredit(Datadictionary datadictionaryByCredit) {
		this.datadictionaryByCredit = datadictionaryByCredit;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Datadictionary getDatadictionaryBySatisfaction() {
		return this.datadictionaryBySatisfaction;
	}

	public void setDatadictionaryBySatisfaction(Datadictionary datadictionaryBySatisfaction) {
		this.datadictionaryBySatisfaction = datadictionaryBySatisfaction;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(Integer postalcode) {
		this.postalcode = postalcode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getLicenseno() {
		return this.licenseno;
	}

	public void setLicenseno(String licenseno) {
		this.licenseno = licenseno;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public Double getCapital() {
		return this.capital;
	}

	public void setCapital(Double capital) {
		this.capital = capital;
	}

	public Double getTurnover() {
		return this.turnover;
	}

	public void setTurnover(Double turnover) {
		this.turnover = turnover;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getBankaccount() {
		return this.bankaccount;
	}

	public void setBankaccount(String bankaccount) {
		this.bankaccount = bankaccount;
	}

	public String getLandtax() {
		return this.landtax;
	}

	public void setLandtax(String landtax) {
		this.landtax = landtax;
	}

	public String getNationaltax() {
		return this.nationaltax;
	}

	public void setNationaltax(String nationaltax) {
		this.nationaltax = nationaltax;
	}

	public Integer getCustomerstatus() {
		return this.customerstatus;
	}

	public void setCustomerstatus(Integer customerstatus) {
		this.customerstatus = customerstatus;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getContactses() {
		return this.contactses;
	}

	public void setContactses(Set contactses) {
		this.contactses = contactses;
	}

	public Set getChurnses() {
		return this.churnses;
	}

	public void setChurnses(Set churnses) {
		this.churnses = churnses;
	}

	public Set getAssociations() {
		return this.associations;
	}

	public void setAssociations(Set associations) {
		this.associations = associations;
	}

}
