package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Datadictionary generated by hbm2java
 */
public class Datadictionary implements java.io.Serializable {


	private Integer ddid;
	private String ddtype;
	private String ddname;
	private Integer ddvalue;
	private String editorable;
	private Set services = new HashSet(0);
	private Set customersForRelationshiplevel = new HashSet(0);
	private Set customersForCredit = new HashSet(0);
	private Set customersForSatisfaction = new HashSet(0);

	public Datadictionary() {
	}

	public Datadictionary(String ddtype, String ddname, String editorable) {
		this.ddtype = ddtype;
		this.ddname = ddname;
		this.editorable = editorable;
	}

	public Datadictionary(String ddtype, String ddname, Integer ddvalue, String editorable, Set services,
			Set customersForRelationshiplevel, Set customersForCredit, Set customersForSatisfaction) {
		this.ddtype = ddtype;
		this.ddname = ddname;
		this.ddvalue = ddvalue;
		this.editorable = editorable;
		this.services = services;
		this.customersForRelationshiplevel = customersForRelationshiplevel;
		this.customersForCredit = customersForCredit;
		this.customersForSatisfaction = customersForSatisfaction;
	}
	
	public Datadictionary(Integer ddid, String ddtype, String ddname, Integer ddvalue, String editorable) {
		super();
		this.ddid = ddid;
		this.ddtype = ddtype;
		this.ddname = ddname;
		this.ddvalue = ddvalue;
		this.editorable = editorable;
	}

	public Integer getDdid() {
		return this.ddid;
	}

	public void setDdid(Integer ddid) {
		this.ddid = ddid;
	}

	public String getDdtype() {
		return this.ddtype;
	}

	public void setDdtype(String ddtype) {
		this.ddtype = ddtype;
	}

	public String getDdname() {
		return this.ddname;
	}

	public void setDdname(String ddname) {
		this.ddname = ddname;
	}

	public Integer getDdvalue() {
		return this.ddvalue;
	}

	public void setDdvalue(Integer ddvalue) {
		this.ddvalue = ddvalue;
	}

	public String getEditorable() {
		return this.editorable;
	}

	public void setEditorable(String editorable) {
		this.editorable = editorable;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

	public Set getCustomersForRelationshiplevel() {
		return this.customersForRelationshiplevel;
	}

	public void setCustomersForRelationshiplevel(Set customersForRelationshiplevel) {
		this.customersForRelationshiplevel = customersForRelationshiplevel;
	}

	public Set getCustomersForCredit() {
		return this.customersForCredit;
	}

	public void setCustomersForCredit(Set customersForCredit) {
		this.customersForCredit = customersForCredit;
	}

	public Set getCustomersForSatisfaction() {
		return this.customersForSatisfaction;
	}

	public void setCustomersForSatisfaction(Set customersForSatisfaction) {
		this.customersForSatisfaction = customersForSatisfaction;
	}

}
