package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private Integer jobno;
	private String jobname;
	private Set jobprivaleges = new HashSet(0);
	private Set users = new HashSet(0);
	private String privs;

	public Job() {
	}
	
	public Job(Integer jobno, String jobname) {
		this.jobno = jobno;
		this.jobname = jobname;
	}

	public Job(String jobname, Set jobprivaleges, Set users) {
		this.jobname = jobname;
		this.jobprivaleges = jobprivaleges;
		this.users = users;
	}


	public Integer getJobno() {
		return this.jobno;
	}

	public void setJobno(Integer jobno) {
		this.jobno = jobno;
	}

	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}
	
	public String getPrivs() {
		return privs;
	}

	public void setPrivs(String privs) {
		this.privs = privs;
	}

	public Set getJobprivaleges() {
		return this.jobprivaleges;
	}

	public void setJobprivaleges(Set jobprivaleges) {
		this.jobprivaleges = jobprivaleges;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
