package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer newsid;
	private User user;
	private String newsname;
	private String newstitle;
	private Date issuetime;
	private String newscontent;
	private String newsfrom;

	public News() {
	}

	public News(User user, String newsname, String newstitle, Date issuetime, String newscontent, String newsfrom) {
		this.user = user;
		this.newsname = newsname;
		this.newstitle = newstitle;
		this.issuetime = issuetime;
		this.newscontent = newscontent;
		this.newsfrom = newsfrom;
	}

	public Integer getNewsid() {
		return this.newsid;
	}

	public void setNewsid(Integer newsid) {
		this.newsid = newsid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNewsname() {
		return this.newsname;
	}

	public void setNewsname(String newsname) {
		this.newsname = newsname;
	}

	public String getNewstitle() {
		return this.newstitle;
	}

	public void setNewstitle(String newstitle) {
		this.newstitle = newstitle;
	}

	public Date getIssuetime() {
		return this.issuetime;
	}

	public void setIssuetime(Date issuetime) {
		this.issuetime = issuetime;
	}

	public String getNewscontent() {
		return this.newscontent;
	}

	public void setNewscontent(String newscontent) {
		this.newscontent = newscontent;
	}

	public String getNewsfrom() {
		return this.newsfrom;
	}

	public void setNewsfrom(String newsfrom) {
		this.newsfrom = newsfrom;
	}

}
