package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

/**
 * Offer generated by hbm2java
 */
public class Offer implements java.io.Serializable {

	private int offerid;
	private Status status;
	private User user;
	private Double productoffer;
	private Double actualizeoffer;
	private Double pmoffer;
	private Double ssoffer;
	private Double paloffer;
	private Double totaloffer;

	public Offer() {
	}

	public Offer(int offerid) {
		this.offerid = offerid;
	}

	public Offer(int offerid, Status status, User user, Double productoffer, Double actualizeoffer, Double pmoffer,
			Double ssoffer, Double paloffer, Double totaloffer) {
		this.offerid = offerid;
		this.status = status;
		this.user = user;
		this.productoffer = productoffer;
		this.actualizeoffer = actualizeoffer;
		this.pmoffer = pmoffer;
		this.ssoffer = ssoffer;
		this.paloffer = paloffer;
		this.totaloffer = totaloffer;
	}

	public int getOfferid() {
		return this.offerid;
	}

	public void setOfferid(int offerid) {
		this.offerid = offerid;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Double getProductoffer() {
		return this.productoffer;
	}

	public void setProductoffer(Double productoffer) {
		this.productoffer = productoffer;
	}

	public Double getActualizeoffer() {
		return this.actualizeoffer;
	}

	public void setActualizeoffer(Double actualizeoffer) {
		this.actualizeoffer = actualizeoffer;
	}

	public Double getPmoffer() {
		return this.pmoffer;
	}

	public void setPmoffer(Double pmoffer) {
		this.pmoffer = pmoffer;
	}

	public Double getSsoffer() {
		return this.ssoffer;
	}

	public void setSsoffer(Double ssoffer) {
		this.ssoffer = ssoffer;
	}

	public Double getPaloffer() {
		return this.paloffer;
	}

	public void setPaloffer(Double paloffer) {
		this.paloffer = paloffer;
	}

	public Double getTotaloffer() {
		return this.totaloffer;
	}

	public void setTotaloffer(Double totaloffer) {
		this.totaloffer = totaloffer;
	}

}
