package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private String orderid;
	private Status status;
	private Customer customer;
	private Date ordertime;
	private String orderaddress;
	private Double orderprice;
	private Set productinfos = new HashSet(0);

	public Order() {
	}

	public Order(String orderid) {
		this.orderid = orderid;
	}

	public Order(String orderid, Status status, Customer customer, Date ordertime, String orderaddress,
			Double orderprice, Set productinfos) {
		this.orderid = orderid;
		this.status = status;
		this.customer = customer;
		this.ordertime = ordertime;
		this.orderaddress = orderaddress;
		this.orderprice = orderprice;
		this.productinfos = productinfos;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrdertime() {
		return this.ordertime;
	}

	public void setOrdertime(Date ordertime) {
		this.ordertime = ordertime;
	}

	public String getOrderaddress() {
		return this.orderaddress;
	}

	public void setOrderaddress(String orderaddress) {
		this.orderaddress = orderaddress;
	}

	public Double getOrderprice() {
		return this.orderprice;
	}

	public void setOrderprice(Double orderprice) {
		this.orderprice = orderprice;
	}

	public Set getProductinfos() {
		return this.productinfos;
	}

	public void setProductinfos(Set productinfos) {
		this.productinfos = productinfos;
	}

}
