package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer planid;
	private Status status;
	private Chance chance;
	private String plancontent;
	private Date plantime;
	private String planback;

	public Plan() {
	}

	public Plan(Status status, Date plantime) {
		this.status = status;
		this.plantime = plantime;
	}

	public Plan(Status status, Chance chance, String plancontent, Date plantime, String planback) {
		this.status = status;
		this.chance = chance;
		this.plancontent = plancontent;
		this.plantime = plantime;
		this.planback = planback;
	}

	public Integer getPlanid() {
		return this.planid;
	}

	public void setPlanid(Integer planid) {
		this.planid = planid;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Chance getChance() {
		return this.chance;
	}

	public void setChance(Chance chance) {
		this.chance = chance;
	}

	public String getPlancontent() {
		return this.plancontent;
	}

	public void setPlancontent(String plancontent) {
		this.plancontent = plancontent;
	}

	public Date getPlantime() {
		return this.plantime;
	}

	public void setPlantime(Date plantime) {
		this.plantime = plantime;
	}

	public String getPlanback() {
		return this.planback;
	}

	public void setPlanback(String planback) {
		this.planback = planback;
	}

}
