package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege implements java.io.Serializable {

	private Integer privilegeid;
	private Privilege privilege;
	private String privilegename;
	private String privilegetype;
	private String privilegeaddress;
	private String privilegecode;
	private Set privileges = new HashSet(0);
	private Set jobprivaleges = new HashSet(0);

	public Privilege() {
	}

	public Privilege(Privilege privilege, String privilegename, String privilegetype, String privilegeaddress,
			String privilegecode, Set privileges, Set jobprivaleges) {
		this.privilege = privilege;
		this.privilegename = privilegename;
		this.privilegetype = privilegetype;
		this.privilegeaddress = privilegeaddress;
		this.privilegecode = privilegecode;
		this.privileges = privileges;
		this.jobprivaleges = jobprivaleges;
	}

	public Integer getPrivilegeid() {
		return this.privilegeid;
	}

	public void setPrivilegeid(Integer privilegeid) {
		this.privilegeid = privilegeid;
	}

	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	public String getPrivilegename() {
		return this.privilegename;
	}

	public void setPrivilegename(String privilegename) {
		this.privilegename = privilegename;
	}

	public String getPrivilegetype() {
		return this.privilegetype;
	}

	public void setPrivilegetype(String privilegetype) {
		this.privilegetype = privilegetype;
	}

	public String getPrivilegeaddress() {
		return this.privilegeaddress;
	}

	public void setPrivilegeaddress(String privilegeaddress) {
		this.privilegeaddress = privilegeaddress;
	}

	public String getPrivilegecode() {
		return this.privilegecode;
	}

	public void setPrivilegecode(String privilegecode) {
		this.privilegecode = privilegecode;
	}

	public Set getPrivileges() {
		return this.privileges;
	}

	public void setPrivileges(Set privileges) {
		this.privileges = privileges;
	}

	public Set getJobprivaleges() {
		return this.jobprivaleges;
	}

	public void setJobprivaleges(Set jobprivaleges) {
		this.jobprivaleges = jobprivaleges;
	}

}
