package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

/**
 * Productinfo generated by hbm2java
 */
public class Productinfo implements java.io.Serializable {

	private Integer productinfoid;
	private Order order;
	private Product product;
	private Integer productcount;

	public Productinfo() {
	}

	public Productinfo(Order order, Product product, Integer productcount) {
		this.order = order;
		this.product = product;
		this.productcount = productcount;
	}

	public Integer getProductinfoid() {
		return this.productinfoid;
	}

	public void setProductinfoid(Integer productinfoid) {
		this.productinfoid = productinfoid;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getProductcount() {
		return this.productcount;
	}

	public void setProductcount(Integer productcount) {
		this.productcount = productcount;
	}

}
