package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	public Product() {
		//super();
	}

	public Product(Integer productid, String productname,String producttype, Double productprice,String productonce,
			String productunit,String productoutline) {
		super();
		this.productid = productid;
		this.productname = productname;
		this.producttype = producttype;
		this.productprice = productprice;
		this.productonce = productonce;
		this.productunit = productunit;
		this.productoutline = productoutline;
	}

	private Integer productid;
	private String productname;
	private Double productprice;
	private String productunit;
	private String producttype;
	private String productonce;
	private String productoutline;
	private Set productinfos = new HashSet(0);

	

	public Product(String productname, Double productprice, String productunit, String producttype, String productonce,
			String productoutline, Set productinfos) {
		this.productname = productname;
		this.productprice = productprice;
		this.productunit = productunit;
		this.producttype = producttype;
		this.productonce = productonce;
		this.productoutline = productoutline;
		this.productinfos = productinfos;
	}

	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public Double getProductprice() {
		return this.productprice;
	}

	public void setProductprice(Double productprice) {
		this.productprice = productprice;
	}

	public String getProductunit() {
		return this.productunit;
	}

	public void setProductunit(String productunit) {
		this.productunit = productunit;
	}

	public String getProducttype() {
		return this.producttype;
	}

	public void setProducttype(String producttype) {
		this.producttype = producttype;
	}

	public String getProductonce() {
		return this.productonce;
	}

	public void setProductonce(String productonce) {
		this.productonce = productonce;
	}

	public String getProductoutline() {
		return this.productoutline;
	}

	public void setProductoutline(String productoutline) {
		this.productoutline = productoutline;
	}

	public Set getProductinfos() {
		return this.productinfos;
	}

	public void setProductinfos(Set productinfos) {
		this.productinfos = productinfos;
	}

}
