package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private int serviceid;
	private User userByCreateuserid;
	private User userByAssignuserid;
	private User userByDisposeuserid;
	private Datadictionary datadictionary;
	private Customer customer;
	private Status status;
	private String serviceoutline;
	private String servicerequest;
	private Date createtime;
	private String serviceresponse;
	private Date assigntime;
	private String serviceresult;
	private Integer satisfaction;
	private Date disposetime;

	public Service() {
	}

	public Service(int serviceid) {
		this.serviceid = serviceid;
	}

	public Service(int serviceid, User userByCreateuserid, User userByAssignuserid, User userByDisposeuserid,
			Datadictionary datadictionary, Customer customer, Status status, String serviceoutline,
			String servicerequest, Date createtime, String serviceresponse, Date assigntime, String serviceresult,
			Integer satisfaction, Date disposetime) {
		this.serviceid = serviceid;
		this.userByCreateuserid = userByCreateuserid;
		this.userByAssignuserid = userByAssignuserid;
		this.userByDisposeuserid = userByDisposeuserid;
		this.datadictionary = datadictionary;
		this.customer = customer;
		this.status = status;
		this.serviceoutline = serviceoutline;
		this.servicerequest = servicerequest;
		this.createtime = createtime;
		this.serviceresponse = serviceresponse;
		this.assigntime = assigntime;
		this.serviceresult = serviceresult;
		this.satisfaction = satisfaction;
		this.disposetime = disposetime;
	}

	public int getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(int serviceid) {
		this.serviceid = serviceid;
	}

	public User getUserByCreateuserid() {
		return this.userByCreateuserid;
	}

	public void setUserByCreateuserid(User userByCreateuserid) {
		this.userByCreateuserid = userByCreateuserid;
	}

	public User getUserByAssignuserid() {
		return this.userByAssignuserid;
	}

	public void setUserByAssignuserid(User userByAssignuserid) {
		this.userByAssignuserid = userByAssignuserid;
	}

	public User getUserByDisposeuserid() {
		return this.userByDisposeuserid;
	}

	public void setUserByDisposeuserid(User userByDisposeuserid) {
		this.userByDisposeuserid = userByDisposeuserid;
	}

	public Datadictionary getDatadictionary() {
		return this.datadictionary;
	}

	public void setDatadictionary(Datadictionary datadictionary) {
		this.datadictionary = datadictionary;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getServiceoutline() {
		return this.serviceoutline;
	}

	public void setServiceoutline(String serviceoutline) {
		this.serviceoutline = serviceoutline;
	}

	public String getServicerequest() {
		return this.servicerequest;
	}

	public void setServicerequest(String servicerequest) {
		this.servicerequest = servicerequest;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getServiceresponse() {
		return this.serviceresponse;
	}

	public void setServiceresponse(String serviceresponse) {
		this.serviceresponse = serviceresponse;
	}

	public Date getAssigntime() {
		return this.assigntime;
	}

	public void setAssigntime(Date assigntime) {
		this.assigntime = assigntime;
	}

	public String getServiceresult() {
		return this.serviceresult;
	}

	public void setServiceresult(String serviceresult) {
		this.serviceresult = serviceresult;
	}

	public Integer getSatisfaction() {
		return this.satisfaction;
	}

	public void setSatisfaction(Integer satisfaction) {
		this.satisfaction = satisfaction;
	}

	public Date getDisposetime() {
		return this.disposetime;
	}

	public void setDisposetime(Date disposetime) {
		this.disposetime = disposetime;
	}

}
