package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

/**
 * Slideshow generated by hbm2java
 */
public class Slideshow implements java.io.Serializable {

	private Integer slideshowid;
	private User user;
	private String slideshowname;

	public Slideshow() {
	}

	public Slideshow(User user, String slideshowname) {
		this.user = user;
		this.slideshowname = slideshowname;
	}

	public Integer getSlideshowid() {
		return this.slideshowid;
	}

	public void setSlideshowid(Integer slideshowid) {
		this.slideshowid = slideshowid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSlideshowname() {
		return this.slideshowname;
	}

	public void setSlideshowname(String slideshowname) {
		this.slideshowname = slideshowname;
	}

}
