package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

/**
 * StatusId generated by hbm2java
 */
public class StatusId implements java.io.Serializable {

	private int statusid;
	private int statuestype;

	public StatusId() {
	}

	public StatusId(int statusid, int statuestype) {
		this.statusid = statusid;
		this.statuestype = statuestype;
	}

	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	public int getStatuestype() {
		return this.statuestype;
	}

	public void setStatuestype(int statuestype) {
		this.statuestype = statuestype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StatusId))
			return false;
		StatusId castOther = (StatusId) other;

		return (this.getStatusid() == castOther.getStatusid()) && (this.getStatuestype() == castOther.getStatuestype());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStatusid();
		result = 37 * result + this.getStatuestype();
		return result;
	}

}
