package com.jokerdemo.crm.domain;
// Generated 2017-10-12 17:23:36 by Hibernate Tools 3.5.0.Final

/**
 * Ware generated by hbm2java
 */
public class Ware implements java.io.Serializable {

	private int wareid;
	private String wareproduct;
	private String ware;
	private String warest;
	private Integer productnum;
	private String wareoutline;

	public Ware() {
	}

	public Ware(int wareid) {
		this.wareid = wareid;
	}

	public Ware(int wareid, String wareproduct, String ware, String warest, Integer productnum, String wareoutline) {
		this.wareid = wareid;
		this.wareproduct = wareproduct;
		this.ware = ware;
		this.warest = warest;
		this.productnum = productnum;
		this.wareoutline = wareoutline;
	}

	public int getWareid() {
		return this.wareid;
	}

	public void setWareid(int wareid) {
		this.wareid = wareid;
	}

	public String getWareproduct() {
		return this.wareproduct;
	}

	public void setWareproduct(String wareproduct) {
		this.wareproduct = wareproduct;
	}

	public String getWare() {
		return this.ware;
	}

	public void setWare(String ware) {
		this.ware = ware;
	}

	public String getWarest() {
		return this.warest;
	}

	public void setWarest(String warest) {
		this.warest = warest;
	}

	public Integer getProductnum() {
		return this.productnum;
	}

	public void setProductnum(Integer productnum) {
		this.productnum = productnum;
	}

	public String getWareoutline() {
		return this.wareoutline;
	}

	public void setWareoutline(String wareoutline) {
		this.wareoutline = wareoutline;
	}

}
